### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Goodswine** [Cicini/melancholianna#2]
I’m trying to play the game, but there’s no sound to it

**Comment by Cicini** [comment]
> I’m trying to play the game, but there’s no sound to it

This is probably due to a network issue and the audio file was not fully downloaded while the game was in progress. As far as I know, access to Cloudflare and GitHub Pages is erratic in some areas. If there is still no sound after refreshing, I recommend that you download it to local deployment and run it, or search the web and download the standalone version.
